steps:
# Install dependencies
- name: node
  entrypoint: yarn
  args: ['install']
  dir: 'Tema_3/'
# Run tests
# - name: node
#   entrypoint: yarn
#   args: ['test']
# Run custom commands
- name: node
  entrypoint: yarn
  args: ['start']